// Static fallback datasets for WeatherPortalView (extracted outside component body to avoid heap thrashing and GC churn on low-end hardware)

export interface HourlyDetailItem {
  id: string;
  hour: string;
  temp: number;
  realFeel: number;
  realFeelShade: number;
  condition: string;
  icon: string;
  rainProb: string;
  rainMm: number;
  wind: string;
  windGusts: string;
  humidity: number;
  indoorHumidity: string;
  dewPoint: number;
  uvIndex: string;
  brightnessIndex: string;
  cloudCover: string;
  visibility: string;
  cloudCeiling: string;
  tideLevel: number;
  floodRisk: "SAFE" | "LOW" | "MODERATE" | "CRITICAL" | "DANGER" | "WARNING";
  pumpsArmed: string;
  vulnerability: string;
}

export interface TenDayForecastItem {
  day: string;
  date: string;
  icon: string;
  hiTemp: number;
  loTemp: number;
  rainProb: string;
  rainMm: number;
  summary: string;
  realFeel: number;
  realFeelShade: number;
  maxUv: string;
  wind: string;
  precipHours: string;
  rainHours: string;
  tidePeak: number;
  spsStatus: string;
  vulnerability: string;
  severity: string;
  badgeColor: string;
}

export const STATIC_HOURLY_DETAILS: HourlyDetailItem[] = [
  {
    id: "8 AM",
    hour: "8 AM",
    temp: 28,
    realFeel: 34,
    realFeelShade: 32,
    condition: "Intermittent clouds",
    icon: "🌤️",
    rainProb: "20%",
    rainMm: 0,
    wind: "SW 9 km/h",
    windGusts: "19 km/h",
    humidity: 77,
    indoorHumidity: "77% (Extremely Humid)",
    dewPoint: 24,
    uvIndex: "1.2 (Low)",
    brightnessIndex: "7 (Bright)",
    cloudCover: "61%",
    visibility: "11 km",
    cloudCeiling: "500 m",
    tideLevel: 3.2,
    floodRisk: "SAFE",
    pumpsArmed: "2 SPS Operational",
    vulnerability: "Normal flow in Dadar & Kurla"
  },
  {
    id: "9 AM",
    hour: "9 AM",
    temp: 29,
    realFeel: 37,
    realFeelShade: 33,
    condition: "Intermittent clouds",
    icon: "🌤️",
    rainProb: "20%",
    rainMm: 0,
    wind: "SW 9 km/h",
    windGusts: "20 km/h",
    humidity: 76,
    indoorHumidity: "76% (Extremely Humid)",
    dewPoint: 24,
    uvIndex: "3.5 (Moderate)",
    brightnessIndex: "8 (Bright)",
    cloudCover: "58%",
    visibility: "11 km",
    cloudCeiling: "520 m",
    tideLevel: 3.4,
    floodRisk: "SAFE",
    pumpsArmed: "2 SPS Operational",
    vulnerability: "Normal baseline"
  },
  {
    id: "10 AM",
    hour: "10 AM",
    temp: 30,
    realFeel: 37,
    realFeelShade: 34,
    condition: "Intermittent clouds",
    icon: "🌤️",
    rainProb: "25%",
    rainMm: 2,
    wind: "SW 9 km/h",
    windGusts: "22 km/h",
    humidity: 74,
    indoorHumidity: "74% (Humid)",
    dewPoint: 25,
    uvIndex: "5.8 (High)",
    brightnessIndex: "9 (Intense)",
    cloudCover: "60%",
    visibility: "10 km",
    cloudCeiling: "500 m",
    tideLevel: 3.6,
    floodRisk: "LOW",
    pumpsArmed: "3 SPS Standby",
    vulnerability: "Milan Subway dry"
  },
  {
    id: "11 AM",
    hour: "11 AM",
    temp: 31,
    realFeel: 39,
    realFeelShade: 34,
    condition: "Intermittent clouds",
    icon: "🌤️",
    rainProb: "25%",
    rainMm: 5,
    wind: "W 11 km/h",
    windGusts: "24 km/h",
    humidity: 73,
    indoorHumidity: "73% (Humid)",
    dewPoint: 25,
    uvIndex: "7.2 (Very High)",
    brightnessIndex: "10 (Extreme)",
    cloudCover: "65%",
    visibility: "10 km",
    cloudCeiling: "480 m",
    tideLevel: 3.8,
    floodRisk: "LOW",
    pumpsArmed: "4 SPS Standby",
    vulnerability: "Minor spray at Marine Drive promenade"
  },
  {
    id: "12 PM",
    hour: "12 PM",
    temp: 31,
    realFeel: 39,
    realFeelShade: 35,
    condition: "Mostly cloudy",
    icon: "⛅",
    rainProb: "30%",
    rainMm: 8,
    wind: "W 13 km/h",
    windGusts: "26 km/h",
    humidity: 75,
    indoorHumidity: "75% (Extremely Humid)",
    dewPoint: 25,
    uvIndex: "6.5 (High)",
    brightnessIndex: "8 (Bright)",
    cloudCover: "72%",
    visibility: "10 km",
    cloudCeiling: "450 m",
    tideLevel: 4.0,
    floodRisk: "MODERATE",
    pumpsArmed: "Britannia SPS Active",
    vulnerability: "Hindmata sluice gates closed"
  },
  {
    id: "1 PM",
    hour: "1 PM",
    temp: 32,
    realFeel: 40,
    realFeelShade: 35,
    condition: "Intermittent clouds",
    icon: "🌤️",
    rainProb: "35%",
    rainMm: 12,
    wind: "W 13 km/h",
    windGusts: "28 km/h",
    humidity: 76,
    indoorHumidity: "76% (Extremely Humid)",
    dewPoint: 26,
    uvIndex: "6.0 (High)",
    brightnessIndex: "8 (Bright)",
    cloudCover: "70%",
    visibility: "9 km",
    cloudCeiling: "450 m",
    tideLevel: 4.1,
    floodRisk: "MODERATE",
    pumpsArmed: "6 SPS Active",
    vulnerability: "Spring tide high level surge"
  },
  {
    id: "2 PM",
    hour: "2 PM",
    temp: 31,
    realFeel: 39,
    realFeelShade: 34,
    condition: "Partly sunny",
    icon: "⛅",
    rainProb: "35%",
    rainMm: 15,
    wind: "W 15 km/h",
    windGusts: "30 km/h",
    humidity: 78,
    indoorHumidity: "78% (Extremely Humid)",
    dewPoint: 26,
    uvIndex: "4.5 (Moderate)",
    brightnessIndex: "7 (Bright)",
    cloudCover: "75%",
    visibility: "9 km",
    cloudCeiling: "420 m",
    tideLevel: 4.2,
    floodRisk: "MODERATE",
    pumpsArmed: "6 SPS Active",
    vulnerability: "Sion Priyadarshini water accumulation"
  },
  {
    id: "3 PM",
    hour: "3 PM",
    temp: 31,
    realFeel: 37,
    realFeelShade: 34,
    condition: "Partly sunny",
    icon: "⛅",
    rainProb: "38%",
    rainMm: 22,
    wind: "W 17 km/h",
    windGusts: "32 km/h",
    humidity: 79,
    indoorHumidity: "79% (Extremely Humid)",
    dewPoint: 26,
    uvIndex: "3.2 (Moderate)",
    brightnessIndex: "6 (Fair)",
    cloudCover: "80%",
    visibility: "8 km",
    cloudCeiling: "400 m",
    tideLevel: 4.0,
    floodRisk: "MODERATE",
    pumpsArmed: "7 SPS Active",
    vulnerability: "Kurla LBS Marg slow traffic"
  },
  {
    id: "4 PM",
    hour: "4 PM",
    temp: 31,
    realFeel: 35,
    realFeelShade: 33,
    condition: "Mostly cloudy w/ t-storms",
    icon: "⛈️",
    rainProb: "53%",
    rainMm: 55,
    wind: "W 17 km/h",
    windGusts: "36 km/h",
    humidity: 82,
    indoorHumidity: "82% (Extremely Humid)",
    dewPoint: 26,
    uvIndex: "2.0 (Low)",
    brightnessIndex: "5 (Cloudy)",
    cloudCover: "88%",
    visibility: "6 km",
    cloudCeiling: "350 m",
    tideLevel: 3.8,
    floodRisk: "CRITICAL",
    pumpsArmed: "All 9 SPS Armed",
    vulnerability: "Milan Subway 35cm inundation alert"
  },
  {
    id: "5 PM",
    hour: "5 PM",
    temp: 30,
    realFeel: 35,
    realFeelShade: 32,
    condition: "Partly sunny w/ t-storms",
    icon: "⛈️",
    rainProb: "58%",
    rainMm: 75,
    wind: "W 15 km/h",
    windGusts: "35 km/h",
    humidity: 84,
    indoorHumidity: "84% (Extremely Humid)",
    dewPoint: 26,
    uvIndex: "1.0 (Low)",
    brightnessIndex: "4 (Overcast)",
    cloudCover: "92%",
    visibility: "5 km",
    cloudCeiling: "300 m",
    tideLevel: 3.5,
    floodRisk: "CRITICAL",
    pumpsArmed: "All 9 SPS Armed",
    vulnerability: "Andheri & Milan Subway traffic diverted"
  },
  {
    id: "6 PM",
    hour: "6 PM",
    temp: 30,
    realFeel: 35,
    realFeelShade: 32,
    condition: "Mostly sunny",
    icon: "🌤️",
    rainProb: "49%",
    rainMm: 40,
    wind: "W 15 km/h",
    windGusts: "30 km/h",
    humidity: 83,
    indoorHumidity: "83% (Extremely Humid)",
    dewPoint: 25,
    uvIndex: "0.5 (Low)",
    brightnessIndex: "4 (Dusk)",
    cloudCover: "85%",
    visibility: "7 km",
    cloudCeiling: "380 m",
    tideLevel: 3.1,
    floodRisk: "MODERATE",
    pumpsArmed: "8 SPS Active",
    vulnerability: "Mithi River receding below danger mark"
  },
  {
    id: "7 PM",
    hour: "7 PM",
    temp: 30,
    realFeel: 33,
    realFeelShade: 30,
    condition: "Mostly clear",
    icon: "🌙",
    rainProb: "43%",
    rainMm: 25,
    wind: "W 15 km/h",
    windGusts: "28 km/h",
    humidity: 82,
    indoorHumidity: "82% (Extremely Humid)",
    dewPoint: 25,
    uvIndex: "0.0 (None)",
    brightnessIndex: "0 (Night)",
    cloudCover: "70%",
    visibility: "8 km",
    cloudCeiling: "420 m",
    tideLevel: 2.8,
    floodRisk: "MODERATE",
    pumpsArmed: "6 SPS Active",
    vulnerability: "Thane Reti Bunder discharge clear"
  },
  {
    id: "8 PM",
    hour: "8 PM",
    temp: 29,
    realFeel: 33,
    realFeelShade: 29,
    condition: "Intermittent clouds",
    icon: "🌙",
    rainProb: "47%",
    rainMm: 15,
    wind: "W 13 km/h",
    windGusts: "26 km/h",
    humidity: 83,
    indoorHumidity: "83% (Extremely Humid)",
    dewPoint: 25,
    uvIndex: "0.0 (None)",
    brightnessIndex: "0 (Night)",
    cloudCover: "65%",
    visibility: "8 km",
    cloudCeiling: "450 m",
    tideLevel: 2.5,
    floodRisk: "LOW",
    pumpsArmed: "4 SPS Active",
    vulnerability: "Kurla road waters drained"
  },
  {
    id: "9 PM",
    hour: "9 PM",
    temp: 28,
    realFeel: 31,
    realFeelShade: 28,
    condition: "Mostly cloudy w/ t-storms",
    icon: "⛈️",
    rainProb: "59%",
    rainMm: 45,
    wind: "W 11 km/h",
    windGusts: "26 km/h",
    humidity: 85,
    indoorHumidity: "85% (Extremely Humid)",
    dewPoint: 25,
    uvIndex: "0.0 (None)",
    brightnessIndex: "0 (Night)",
    cloudCover: "80%",
    visibility: "7 km",
    cloudCeiling: "400 m",
    tideLevel: 2.7,
    floodRisk: "MODERATE",
    pumpsArmed: "6 SPS Active",
    vulnerability: "Night surge preparedness alert"
  },
  {
    id: "10 PM",
    hour: "10 PM",
    temp: 28,
    realFeel: 31,
    realFeelShade: 28,
    condition: "Partly cloudy w/ t-storms",
    icon: "⛈️",
    rainProb: "56%",
    rainMm: 35,
    wind: "WSW 11 km/h",
    windGusts: "24 km/h",
    humidity: 86,
    indoorHumidity: "86% (Extremely Humid)",
    dewPoint: 25,
    uvIndex: "0.0 (None)",
    brightnessIndex: "0 (Night)",
    cloudCover: "78%",
    visibility: "8 km",
    cloudCeiling: "420 m",
    tideLevel: 3.0,
    floodRisk: "LOW",
    pumpsArmed: "4 SPS Active",
    vulnerability: "All drainage outfalls monitored"
  },
  {
    id: "11 PM",
    hour: "11 PM",
    temp: 29,
    realFeel: 33,
    realFeelShade: 29,
    condition: "Partly cloudy",
    icon: "🌙",
    rainProb: "47%",
    rainMm: 10,
    wind: "WSW 11 km/h",
    windGusts: "22 km/h",
    humidity: 84,
    indoorHumidity: "84% (Extremely Humid)",
    dewPoint: 25,
    uvIndex: "0.0 (None)",
    brightnessIndex: "0 (Night)",
    cloudCover: "60%",
    visibility: "9 km",
    cloudCeiling: "480 m",
    tideLevel: 3.3,
    floodRisk: "SAFE",
    pumpsArmed: "2 SPS Active",
    vulnerability: "Quiet midnight conditions"
  }
];

export const STATIC_TEN_DAY_FORECAST: TenDayForecastItem[] = [
  {
    day: "MON",
    date: "9/7",
    icon: "🌤️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "55%",
    rainMm: 45,
    summary: "Sun breaking through clouds at times with a stray thunderstorm this afternoon",
    realFeel: 40,
    realFeelShade: 35,
    maxUv: "10.0 (Very High)",
    wind: "W 13 km/h",
    precipHours: "1.5",
    rainHours: "1.5",
    tidePeak: 4.1,
    spsStatus: "6 SPS Armed",
    vulnerability: "Spring tide surge coincidence at Marine Drive & Dadar",
    severity: "AMBER ALERT",
    badgeColor: "text-amber-300 bg-amber-500/20 border-amber-400/40"
  },
  {
    day: "TUE",
    date: "9/8",
    icon: "⛈️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "68%",
    rainMm: 85,
    summary: "Times of clouds and sun with a couple of showers and a thunderstorm in the afternoon",
    realFeel: 39,
    realFeelShade: 34,
    maxUv: "10.0 (Very High)",
    wind: "WNW 15 km/h",
    precipHours: "1.5",
    rainHours: "1.5",
    tidePeak: 4.3,
    spsStatus: "All 9 SPS Armed",
    vulnerability: "Milan & Hindmata Subways under heavy inundation alert",
    severity: "RED ALERT",
    badgeColor: "text-red-300 bg-red-500/25 border-red-400/50 shadow-[0_0_12px_rgba(239,68,68,0.35)]"
  },
  {
    day: "WED",
    date: "9/9",
    icon: "🌤️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "55%",
    rainMm: 40,
    summary: "A stray thunderstorm in the morning; otherwise, times of clouds and sun",
    realFeel: 40,
    realFeelShade: 36,
    maxUv: "10.0 (Very High)",
    wind: "WNW 15 km/h",
    precipHours: "1.5",
    rainHours: "1.5",
    tidePeak: 4.2,
    spsStatus: "7 SPS Active",
    vulnerability: "Kurla LBS Marg morning drainage slowdown",
    severity: "AMBER ALERT",
    badgeColor: "text-amber-300 bg-amber-500/20 border-amber-400/40"
  },
  {
    day: "THU",
    date: "9/10",
    icon: "🌦️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "74%",
    rainMm: 65,
    summary: "Variable cloudiness; morning showers followed by a shower in spots in the afternoon",
    realFeel: 40,
    realFeelShade: 35,
    maxUv: "9.0 (Very High)",
    wind: "WNW 13 km/h",
    precipHours: "2",
    rainHours: "2",
    tidePeak: 4.0,
    spsStatus: "6 SPS Active",
    vulnerability: "Andheri subway intermittent water logging",
    severity: "AMBER ALERT",
    badgeColor: "text-amber-300 bg-amber-500/20 border-amber-400/40"
  },
  {
    day: "FRI",
    date: "9/11",
    icon: "🌧️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "56%",
    rainMm: 30,
    summary: "Mostly cloudy with a little rain",
    realFeel: 39,
    realFeelShade: 36,
    maxUv: "6.0 (High)",
    wind: "WNW 11 km/h",
    precipHours: "1.5",
    rainHours: "1.5",
    tidePeak: 3.6,
    spsStatus: "4 SPS Active",
    vulnerability: "Normal stormwater discharge at Love Grove & Cleveland",
    severity: "MODERATE",
    badgeColor: "text-cyan-300 bg-cyan-500/20 border-cyan-400/30"
  },
  {
    day: "SAT",
    date: "9/12",
    icon: "🌧️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "59%",
    rainMm: 35,
    summary: "Mostly cloudy with a little rain",
    realFeel: 39,
    realFeelShade: 36,
    maxUv: "7.0 (High)",
    wind: "WNW 13 km/h",
    precipHours: "2",
    rainHours: "2",
    tidePeak: 3.3,
    spsStatus: "3 SPS Active",
    vulnerability: "Mithi river level safe at 2.4m below flood mark",
    severity: "MODERATE",
    badgeColor: "text-cyan-300 bg-cyan-500/20 border-cyan-400/30"
  },
  {
    day: "SUN",
    date: "9/13",
    icon: "🌧️",
    hiTemp: 32,
    loTemp: 26,
    rainProb: "59%",
    rainMm: 32,
    summary: "Mostly cloudy; a little rain in the morning followed by a shower in spots in the afternoon",
    realFeel: 39,
    realFeelShade: 36,
    maxUv: "9.0 (Very High)",
    wind: "SW 9 km/h",
    precipHours: "1.5",
    rainHours: "1.5",
    tidePeak: 3.1,
    spsStatus: "2 SPS Standby",
    vulnerability: "Sion Priyadarshini parkway clear",
    severity: "SAFE",
    badgeColor: "text-emerald-300 bg-emerald-500/20 border-emerald-400/30"
  },
  {
    day: "MON",
    date: "9/14",
    icon: "🌧️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "55%",
    rainMm: 25,
    summary: "Mostly cloudy with a little rain",
    realFeel: 38,
    realFeelShade: 35,
    maxUv: "8.0 (Very High)",
    wind: "SW 9 km/h",
    precipHours: "2",
    rainHours: "2",
    tidePeak: 3.0,
    spsStatus: "2 SPS Standby",
    vulnerability: "Normal low-tide gravity discharge operational",
    severity: "SAFE",
    badgeColor: "text-emerald-300 bg-emerald-500/20 border-emerald-400/30"
  },
  {
    day: "TUE",
    date: "9/15",
    icon: "🌧️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "57%",
    rainMm: 30,
    summary: "Mostly cloudy; a little morning rain followed by a shower in spots in the afternoon",
    realFeel: 39,
    realFeelShade: 36,
    maxUv: "7.0 (High)",
    wind: "WSW 6 km/h",
    precipHours: "2.5",
    rainHours: "2.5",
    tidePeak: 3.2,
    spsStatus: "3 SPS Standby",
    vulnerability: "Eastern Express Highway clear",
    severity: "SAFE",
    badgeColor: "text-emerald-300 bg-emerald-500/20 border-emerald-400/30"
  },
  {
    day: "WED",
    date: "9/16",
    icon: "⛅",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "58%",
    rainMm: 28,
    summary: "Cloudy intervals with afternoon passing showers",
    realFeel: 40,
    realFeelShade: 36,
    maxUv: "6.5 (High)",
    wind: "WSW 8 km/h",
    precipHours: "2.0",
    rainHours: "2.0",
    tidePeak: 3.4,
    spsStatus: "3 SPS Active",
    vulnerability: "Thane Reti Bunder outfall clear",
    severity: "SAFE",
    badgeColor: "text-emerald-300 bg-emerald-500/20 border-emerald-400/30"
  },
  {
    day: "THU",
    date: "9/17",
    icon: "🌦️",
    hiTemp: 32,
    loTemp: 26,
    rainProb: "62%",
    rainMm: 45,
    summary: "Humid with morning downpour and broken clouds in afternoon",
    realFeel: 39,
    realFeelShade: 35,
    maxUv: "5.0 (Moderate)",
    wind: "SW 10 km/h",
    precipHours: "2.5",
    rainHours: "2.5",
    tidePeak: 3.7,
    spsStatus: "4 SPS Active",
    vulnerability: "Dadar Hindmata holding tank armed",
    severity: "MODERATE",
    badgeColor: "text-cyan-300 bg-cyan-500/20 border-cyan-400/30"
  },
  {
    day: "FRI",
    date: "9/18",
    icon: "🌧️",
    hiTemp: 32,
    loTemp: 27,
    rainProb: "60%",
    rainMm: 50,
    summary: "Periods of rain",
    realFeel: 41,
    realFeelShade: 37,
    maxUv: "4.0 (Moderate)",
    wind: "WSW 6 km/h",
    precipHours: "3.5",
    rainHours: "3.5",
    tidePeak: 3.9,
    spsStatus: "6 SPS Active",
    vulnerability: "Western suburbs localized water logging advisory",
    severity: "AMBER ALERT",
    badgeColor: "text-amber-300 bg-amber-500/20 border-amber-400/40"
  },
  {
    day: "SAT",
    date: "9/19",
    icon: "⛈️",
    hiTemp: 31,
    loTemp: 26,
    rainProb: "64%",
    rainMm: 70,
    summary: "Cloudy with a couple of showers and a thunderstorm",
    realFeel: 35,
    realFeelShade: 35,
    maxUv: "2.0 (Low)",
    wind: "SW 15 km/h",
    precipHours: "2",
    rainHours: "2",
    tidePeak: 4.1,
    spsStatus: "8 SPS Armed",
    vulnerability: "Milan Subway high-water automated barricades alert",
    severity: "RED ALERT",
    badgeColor: "text-red-300 bg-red-500/25 border-red-400/50 shadow-[0_0_12px_rgba(239,68,68,0.35)]"
  },
  {
    day: "SUN",
    date: "9/20",
    icon: "🌤️",
    hiTemp: 32,
    loTemp: 25,
    rainProb: "58%",
    rainMm: 40,
    summary: "Sun and clouds with a thunderstorm in the afternoon",
    realFeel: 37,
    realFeelShade: 35,
    maxUv: "6.0 (High)",
    wind: "SW 15 km/h",
    precipHours: "2",
    rainHours: "2",
    tidePeak: 3.8,
    spsStatus: "5 SPS Active",
    vulnerability: "Thane Mumbra creek tidal elevation surveillance",
    severity: "AMBER ALERT",
    badgeColor: "text-amber-300 bg-amber-500/20 border-amber-400/40"
  },
  {
    day: "MON",
    date: "9/21",
    icon: "🌤️",
    hiTemp: 31,
    loTemp: 25,
    rainProb: "55%",
    rainMm: 35,
    summary: "A morning thundershower; otherwise, partly sunny",
    realFeel: 38,
    realFeelShade: 34,
    maxUv: "10.0 (Very High)",
    wind: "S 13 km/h",
    precipHours: "1.5",
    rainHours: "1.5",
    tidePeak: 3.5,
    spsStatus: "3 SPS Active",
    vulnerability: "Receding monsoon conditions; normal tidal range",
    severity: "MODERATE",
    badgeColor: "text-cyan-300 bg-cyan-500/20 border-cyan-400/30"
  }
];
